package App;

import Environment.Place;
import Infrastructure.Employees.VehicleDriver;
import Infrastructure.TransmitterGSM;
import Infrastructure.Vehicles.Vehicle;
import Tools.DriversFactory;
import Tools.PlacesFactory;
import Tools.VehiclesFactory;
import Tools.DepotOperations;
import com.sun.scenario.effect.impl.sw.sse.SSEBlend_SRC_OUTPeer;
import com.sun.tools.doclets.formats.html.SourceToHTMLConverter;
import com.sun.xml.internal.bind.v2.TODO;

import java.util.ArrayList;
import java.util.List;

public class Main {

    private List<Vehicle> vehiclesList;

    public static void main(String[] args) {

        // generate list of vehicles available in depot
        // TODO  set place coordinates to depot (1N,1E)
        List<Vehicle> vehiclesList = VehiclesFactory.getVehicles();
        for (Vehicle vehicle : vehiclesList) {
            System.out.println(vehicle.toString());
        }

        // generate list of available drivers
        List<VehicleDriver> driversList = DriversFactory.getDrivers();
        for (VehicleDriver vehicleDriver : driversList) {
            System.out.println(vehicleDriver.toString());
        }

        // available places list - in real life it should be generated by transmitter or from destinations map
        List<Place> placesList = PlacesFactory.getPlaces();
        for (Place place : placesList) {
            System.out.println(place.toString());
        }

        // just chcecking and displaying the place
        Place place;
        place = placesList.get(0);
        System.out.println("Place number zero: ");
        System.out.println(place.getLatitude());
        System.out.println(place.getLongitude());

        // just checking and setting transmitter00
        System.out.println("First transmitter set");
        TransmitterGSM transmitter00 = new TransmitterGSM(0,0,0);
        transmitter00.setLatitude(place.getLatitude());
        transmitter00.setLongitude(place.getLongitude());

        System.out.println("First transmitter position: latitude " +
                transmitter00.getLatitude() + ", longitude: " +
                transmitter00.getLongitude());

        System.out.println("_ - - - - - _ - - - - - _ - - - - - ");

        // get all details from first element of available vehicles list
        System.out.println(vehiclesList.get(0));
        // get registration from first element of available vehicles list
        System.out.println(vehiclesList.get(0).getRegistrationPlate());


        // start to use vehicles, bind with drivers and transmitters
        // vehicles in use should be removed from list of vehicles available in the depot
        List<Vehicle> vehiclesInUseList = new ArrayList<>();
        vehiclesInUseList.add(vehiclesList.get(0));
        vehiclesList.remove(0);



        vehiclesInUseList.get(0).setDriver(driversList.get(0));
        System.out.println("Set driver 0 to vehicleList 0");
        System.out.println(vehiclesInUseList.get(0));
        vehiclesInUseList.get(0).setTransmitter(transmitter00);

        Vehicle startVehicle = vehiclesList.get(0);
        startVehicle.setDriver(driversList.get(0));
        System.out.println(startVehicle.getDriver().getSurname());

        String nameToCheck = "Doe";


        System.out.println(vehiclesInUseList.size());
        System.out.println(vehiclesInUseList.get(0).getDriver().getSurname());

        DepotOperations.findVehicle(vehiclesInUseList, nameToCheck);








        //vehiclesInUseList.add;



    }


}

