package App;

import Environment.Place;
import Infrastructure.Employees.VehicleDriver;
import Infrastructure.TransmitterGSM;
import Infrastructure.Vehicles.Vehicle;
import Tools.DriversFactory;
import Tools.PlacesFactory;
import Tools.VehiclesFactory;
import com.sun.scenario.effect.impl.sw.sse.SSEBlend_SRC_OUTPeer;
import com.sun.tools.doclets.formats.html.SourceToHTMLConverter;

import java.util.ArrayList;
import java.util.List;

public class Main {

    private List<Vehicle> vehiclesList;

    public static void main(String[] args) {

        // avaliable vehicles list
        List<Vehicle> vehiclesList = VehiclesFactory.getVehicles();
        for (Vehicle vehicle : vehiclesList) {
            System.out.println(vehicle.toString());
        }

        // available drivers list
        List<VehicleDriver> driversList = DriversFactory.getDrivers();
        for (VehicleDriver vehicleDriver : driversList) {
            System.out.println(vehicleDriver.toString());
        }

        // available places list - in real life it should be generated by transmitter or from destinations map
        List<Place> placesList = PlacesFactory.getPlaces();
        for (Place place : placesList) {
            System.out.println(place.toString());
        }



        Place place;
        place = placesList.get(0);
        System.out.println("Place number zero: ");
        System.out.println(place.getLatitude());
        System.out.println(place.getLongitude());

        System.out.println("First transmitter set");
        TransmitterGSM transmitter01 = new TransmitterGSM(0,0,0);
        transmitter01.setLatitude(place.getLatitude());
        transmitter01.setLongitude(place.getLongitude());

        System.out.println("First transmitter position");
        System.out.println(transmitter01.getLatitude());
        System.out.println(transmitter01.getLongitude());

        System.out.println("_ - - - - - _ - - - - - _ - - - - - ");


        // start to use vehicles, bind with drivers and transmitters
        List<Vehicle> vehiclesInUseList = new ArrayList<>();
        vehiclesInUseList.add(vehiclesList.get(0));
        vehiclesList.remove(0);

        // get all details from first element of available vehicles list
        System.out.println(vehiclesList.get(0));
        // get registration from first element of available vehicles list
        Vehicle startVehicle = vehiclesList.get(0);
        startVehicle.setDriver(driversList.get(0));
        System.out.println(startVehicle.getDriver().getName());





        Vehicle vehicleInUse = new Vehicle();






        //vehiclesInUseList.add;



    }
}

